/*
 * This source file was generated by the Gradle 'init' task
 */
package irctcc;

import org.junit.jupiter.api.Test;

import ticketBooking.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
     @Test
    public void testDummy() {
        assertTrue(true); // always passes
    }
}
